# Generated by Django 4.1.2 on 2023-02-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="Seyon's Blog", max_length=255),
        ),
    ]
