# Generated by Django 4.1.2 on 2023-03-04 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_post_options_alter_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, max_length=30, upload_to=''),
            preserve_default=False,
        ),
    ]
