# Generated by Django 4.1.2 on 2023-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_post_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(max_length=30, upload_to='media/'),
        ),
    ]
